-- Bundled default configuration.
-- Copy this file to ~/.config/winmgr/init.lua to customize startup config.
return {
  keymap = {
    { key = "h", modifiers = { "control", "option" }, action = { type = "focus_direction", direction = "left" } },
    { key = "l", modifiers = { "control", "option" }, action = { type = "focus_direction", direction = "right" } },
    { key = "k", modifiers = { "control", "option" }, action = { type = "focus_direction", direction = "up" } },
    { key = "j", modifiers = { "control", "option" }, action = { type = "focus_direction", direction = "down" } },
    { key = "u", modifiers = { "control", "option" }, action = { type = "focus_cycle", direction = "previous" } },
    { key = "i", modifiers = { "control", "option" }, action = { type = "focus_cycle", direction = "next" } },
    { key = "p", modifiers = { "control", "option" }, action = { type = "focus_previous" } },
    { key = "h", modifiers = { "control", "option", "shift" }, action = { type = "swap", direction = "left" } },
    { key = "l", modifiers = { "control", "option", "shift" }, action = { type = "swap", direction = "right" } },
    { key = "k", modifiers = { "control", "option", "shift" }, action = { type = "swap", direction = "up" } },
    { key = "j", modifiers = { "control", "option", "shift" }, action = { type = "swap", direction = "down" } },
    { key = "z", modifiers = { "control", "option" }, action = { type = "undo_layout" } },
    { key = "h", modifiers = { "control", "option", "command" }, action = { type = "push", direction = "left" } },
    { key = "l", modifiers = { "control", "option", "command" }, action = { type = "push", direction = "right" } },
    { key = "k", modifiers = { "control", "option", "command" }, action = { type = "push", direction = "up" } },
    { key = "j", modifiers = { "control", "option", "command" }, action = { type = "push", direction = "down" } },
    { key = "a", modifiers = { "control", "option", "command" }, action = { type = "cascade" } },
    { key = "c", modifiers = { "control", "option", "command" }, action = { type = "center" } },
    { key = "e", modifiers = { "control", "option", "command" }, action = { type = "eject" } },
    { key = "m", modifiers = { "control", "option", "command" }, action = { type = "maximize_reset" } },
    { key = "n", modifiers = { "control", "option", "command" }, action = { type = "move_to_next_display" } },
    { key = "s", modifiers = { "control", "option", "command" }, action = { type = "shuffle" } },
    { key = "h", modifiers = { "control", "option", "shift", "command" }, action = { type = "resize_split", direction = "left", delta = 0.25 } },
    { key = "l", modifiers = { "control", "option", "shift", "command" }, action = { type = "resize_split", direction = "right", delta = 0.25 } },
    { key = "k", modifiers = { "control", "option", "shift", "command" }, action = { type = "resize_split", direction = "up", delta = 0.25 } },
    { key = "j", modifiers = { "control", "option", "shift", "command" }, action = { type = "resize_split", direction = "down", delta = 0.25 } },
    { key = "return", modifiers = { "control", "option", "command" }, action = { type = "balance" } },
    { key = "space", modifiers = { "control", "option" }, action = { type = "toggle_pause" } },
    { key = "/", modifiers = { "control", "option" }, action = { type = "show_commands" } },
    { key = "delete", modifiers = { "control", "option" }, action = { type = "reset_layout" } },
  },
  gaps = {
    inner = 0,
    outer = { top = 0, left = 0, bottom = 0, right = 0 },
  },
  drag_modifier = { "shift" },
  zones = {
    { id = "left-half", bounds = { x = 0, y = 0.3, w = 0.2, h = 0.4 }, action = { type = "insert_as_half", direction = "left" } },
    { id = "right-half", bounds = { x = 0.8, y = 0.3, w = 0.2, h = 0.4 }, action = { type = "insert_as_half", direction = "right" } },
    { id = "top-half", bounds = { x = 0.3, y = 0, w = 0.4, h = 0.2 }, action = { type = "insert_as_half", direction = "up" } },
    { id = "bottom-half", bounds = { x = 0.3, y = 0.8, w = 0.4, h = 0.2 }, action = { type = "insert_as_half", direction = "down" } },
    { id = "center", bounds = { x = 0.4, y = 0.4, w = 0.2, h = 0.2 }, action = { type = "insert_as_center" } },
  },
  border = { width = 2, color = "#4DA3FF" },
  hud = { enabled = true, duration_millis = 700 },
  rules = {},
}
